sudo: required
services:
  - docker
# Haven't needed this before to get Docker to work (???)
# https://github.com/travis-ci/travis-ci/issues/5448
dist: trusty

language: python
matrix:
  include:
    - python: '2.7'
      env: DOCKER_BASE_IMAGE=python:2.7-slim
    - python: '3.5'
      env: DOCKER_BASE_IMAGE=python:3.5-slim
    - python: pypy
      # Disable Docker tests on PyPy: there are weird permissions issues
      env: PYENV_VERSION=pypy-5.4.1 PYENV_VERSION_STRING='PyPy 5.4.1' NO_DOCKER=1 NO_COVERAGE=1
cache:
  - pip
  - directories:
    - ~/.pyenv_cache

before_install:
  - |
    if [[ -n "$PYENV_VERSION" ]]; then
      git clone https://github.com/praekeltfoundation/travis-pyenv.git ~/travis-pyenv
      source ~/travis-pyenv/setup-pyenv.sh
    fi
  - pip install --upgrade pip
install:
  - pip install -r requirements-dev.txt
  - if [[ -z "$NO_COVERAGE" ]]; then pip install codecov; fi

before_script:
  - if [[ -z "$NO_COVERAGE" ]]; then COV_OPT='--cov'; fi
script:
  - pytest "$COV_OPT"
  - flake8 .
  - if [[ -z "$NO_DOCKER" ]]; then ./docker-test.sh fi

after_success:
  - if [[ -z "$NO_COVERAGE" ]]; then codecov; fi
