sudo: required  # Need sudo to run tests that change users

language: python
matrix:
  include:
    - python: '2.7'
    - python: '3.5'
    - python: pypy
      env: PYENV_VERSION=pypy-5.4.1 PYENV_VERSION_STRING='PyPy 5.4.1' PYENV_ROOT=~/.travis-pyenv NO_COVERAGE=1
cache:
  - pip
  - directories:
    - ~/.pyenv_cache

before_install:
  - |
    if [[ -n "$PYENV_VERSION" ]]; then
      git clone https://github.com/praekeltfoundation/travis-pyenv.git ~/travis-pyenv
      source ~/travis-pyenv/setup-pyenv.sh
    fi
  - pip install --upgrade pip
install:
  - pip install -r requirements-dev.txt
  - if [[ -z "$NO_COVERAGE" ]]; then pip install codecov; fi

before_script:
  - if [[ -z "$NO_COVERAGE" ]]; then COV_OPT='--cov'; fi
script:
  # Disable pytest cache to avoid sudo permissions issues
  - sudo -E pytest -p no:cacheprovider "$COV_OPT"
  - flake8 .

after_success:
  - if [[ -z "$NO_COVERAGE" ]]; then codecov; fi
