sudo: required
services:
    - docker
# Haven't needed this before to get Docker to work (???)
# https://github.com/travis-ci/travis-ci/issues/5448
dist: trusty

language: python
matrix:
  include:
    - python: '2.7'
      env: DOCKER_IMAGE=python:2.7-slim
    - python: '3.5'
      env: DOCKER_IMAGE=python:3.5-slim
    - python: pypy
      env: PYENV_VERSION=pypy-5.4.1 PYENV_VERSION_STRING='PyPy 5.4.1' PYENV_ROOT=~/.travis-pyenv DOCKER_IMAGE=pypy:2-5.4.1-slim NO_COVERAGE=1
cache:
  - pip
  - directories:
    - ~/.pyenv_cache

before_install:
  - |
    if [[ -n "$PYENV_VERSION" ]]; then
      git clone https://github.com/praekeltfoundation/travis-pyenv.git ~/travis-pyenv
      source ~/travis-pyenv/setup-pyenv.sh
    fi
  - pip install --upgrade pip
install:
  - docker pull $DOCKER_IMAGE
  - pip install flake8
  - if [[ -z "$NO_COVERAGE" ]]; then pip install codecov; fi

before_script:
  - if [[ -z "$NO_COVERAGE" ]]; then COV_OPT='--cov'; fi
script:
  # Run tests inside a container to get a vaguely consistent environment
  - docker run --rm -v "$(pwd)":/pydexec -w /pydexec $DOCKER_IMAGE /bin/sh -c
      "pip install -r requirements-dev.txt && pytest $COV_OPT"
  - flake8 .

after_success:
  - if [[ -z "$NO_COVERAGE" ]]; then codecov; fi
