sudo: required
services:
    - docker
# Haven't needed this before to get Docker to work (???)
# https://github.com/travis-ci/travis-ci/issues/5448
dist: trusty

language: python
env:
  - DOCKER_IMAGE=python:2.7-slim
  - DOCKER_IMAGE=python:3.5-slim
  - DOCKER_IMAGE=python:3.6-slim
  - DOCKER_IMAGE=pypy:3-slim

install:
  - docker pull $DOCKER_IMAGE
  - pip install codecov

before_script:
  # Use our wheelhouse mirror to get a built subprocess32 module
  - |
    SCRIPT='set -x \
      && pip install --no-cache \
        --extra-index-url https://jessie.wheelhouse.praekelt.org/simple \
        -r requirements-dev.txt \
      && coverage run "$(which pytest)" \
      && coverage report -m && coverage xml \
      && flake8 .'
script:
  # Run tests inside a container to get a vaguely consistent environment
  - docker run --rm -v "$(pwd)":/pydexec -w /pydexec $DOCKER_IMAGE /bin/sh -c "$SCRIPT"

after_success:
  - codecov
